services:
  payload:
    build: .
    container_name: nanotestcms
    image: nanotestcms:latest
    restart: unless-stopped
    ports:
      - '3301:3301'
    volumes:
      - nanotestcms-data:/app/data

volumes:
  nanotestcms-data:
    external: true
