services:
  payload:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nanotestcms-dev
    image: nanotestcms-dev:latest
    restart: unless-stopped
    ports:
      - '3000:3000'  # Default Next.js dev port
    volumes:
      - .:/app      # Mount the current directory for live-reload
      - /app/node_modules  # Prevent host/node_modules conflicts
      - nanotestcms-dev-data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0

volumes:
  nanotestcms-dev-data:
    driver: local
