services:
  payload:
    build: .
    container_name: nanotestcms
    image: nanotestcms:latest
    restart: unless-stopped
    ports:
      - '3301:3301'
    volumes:
      - nanotestcms-data:/app/data
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URI: "mongodb://172.17.0.1:27017/nanotest"

volumes:
  nanotestcms-data:
    external: true
